name: iOS Dev Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.7" # Specify the Node.js version you are using

      - name: Install dependencies
        run: |
          npm install
          cd ios
          pod install --repo-update

      - name: Clear Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Decode and install signing certificate
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security set-keychain-settings -lut 7200 build.keychain
          security unlock-keychain -p "" build.keychain

      - name: Decode and install provisioning profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Verify Simulators
        run: |
          echo "Available simulators:"
          xcrun simctl list

      - name: Build the app for iOS
        run: |
          cd ios
          xcodebuild clean build \
            -workspace ManojDemoapp.xcworkspace \
            -scheme ManojDemoapp \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            CODE_SIGN_IDENTITY="iPhone Developer" \  # Ensure you set this for development builds
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGN_ENTITLEMENTS="ios/ManojDemoapp/ManojDemoapp.entitlements" # Only if you require entitlements

      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: ios/build/ManojDemoapp.app # Update this path to reflect where your .app is generated
