name: Build iOS with Code Signing

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd ios
          pod install

      - name: Set Up Code Signing
        run: |
          # Decode and install the certificate
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security set-keychain-settings -lut 7200 build.keychain

          # Decode and install the provisioning profile
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Clean Build Folder
        run: |
          cd ios
          xcodebuild clean -workspace ManojDemoapp.xcworkspace -scheme ManojDemoappScheme -configuration Debug

      - name: Build iOS Debug
        run: |
          cd ios
          xcodebuild build -workspace ManojDemoapp.xcworkspace -scheme ManojDemoappScheme -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5'

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: ios/build/ManojDemoapp.app
